name: Automated tests

on:
  push

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: |
          Invoke-WebRequest -Uri 'https://dl.google.com/chrome/install/latest/chrome_installer.exe' -OutFile '$env:TEMP\chrome_installer.exe' -UseBasicParsing 
          Start-Process -FilePath '$env:TEMP\chrome_installer.exe' -ArgumentList '/install', '/silent', '/close-when-done' -NoNewWindow -Wait
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
